WebDoAnTN/Models/CMT.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDoAnTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMT
    {
        public string SoCMT { get; set; }
        public string HoTen { get; set; }
        public string TenGoiKhac { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string QueQuan { get; set; }
        public string NoiThuongTru { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public Nullable<int> Type { get; set; }
        public string QuocTich { get; set; }
        public Nullable<System.DateTime> GiaTriDen { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string DauVetRieng { get; set; }
    }
}

WebDoAnTN/Controllers/QuanlyhocsinhController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDoAnTN.Models;

namespace WebDoAnTN.Controllers
{
    public class QuanlyhocsinhController : Controller
    {
       dbXulyTThsEntities  db = new dbXulyTThsEntities();
       Xuly xulyLoi = new Xuly();
        // GET: Quanlyhocsinh
        public ActionResult Index()
        {
            return View();
        }
        #region Thêm học sinh 
        [HttpGet]
        public ActionResult ThemHocsinh()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemHocsinh(HOCSINH hocsinh)
        {
            if (ModelState.IsValid)
            {
                if(hocsinh.TenHS!=null)
                {
                    db.HOCSINHs.Add(hocsinh);
                    db.SaveChanges();
                    Session["hocsinh"] = hocsinh.TenHS;
                    Session["id_hs"] = hocsinh.id;
                    return RedirectToAction("Index");
                }
                return View(hocsinh);
            }
            return View(hocsinh);
        }

        #endregion

        #region Chứng minh thư
        [HttpGet]
        public ActionResult CMT()
        {
            return View();
        }
        public JsonResult LoadFormCMT()
        {
            return Json("", JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult themCMT(CMT cmt)
        {
            if (ModelState.IsValid)
            {
                int id_hs =(int)Session["id_hs"];
                db.CMTs.Add(cmt);
                //Tự động add thêm thông tin cmt vào bảng HOCSINH
                HOCSINH hs = db.HOCSINHs.SingleOrDefault(n => n.id == id_hs);
                hs.SoCMT = cmt.SoCMT;
                db.SaveChanges();
                if(xulyLoi.CheckString(hs.TenHS,cmt.HoTen)==false){
                    Session["Loi"] = "Họ tên giữa Học sinh và chứng minh thư có sự khác nhau";
                }
                else { Session["Loi"] = "Đúng"; }
                return Json(cmt, JsonRequestBehavior.AllowGet);
            }
            return Json(cmt, JsonRequestBehavior.AllowGet);

        }
    #endregion //End Chứng minh thư

        #region Giấy khai sinh
        [HttpGet]
        public ActionResult ThemGiaykhaisinh()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemGiaykhaisinh(GIAYKHAISINH gks)
        {
            if(ModelState.IsValid)
            {
                db.GIAYKHAISINHs.Add(gks);               
                db.SaveChanges();
                //Tự động add thêm thông tin GKS vào bảng HOCSINH
                int id_hs = (int)Session["id_hs"];
                HOCSINH hs = db.HOCSINHs.SingleOrDefault(n => n.id == id_hs);  
                //dua ra giay khai sinh vua them vào (nam ơ vi tri cuoi cung)
                GIAYKHAISINH newG = db.GIAYKHAISINHs.ToList().Last();
                hs.id_GKS = newG.id;
                //Lưu lại dữ liệu bảng Học Sinh
                db.Entry(hs).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

               
                return RedirectToAction("Index");
            }
            return View(gks);
        }
        #endregion end Giay khai sinh

        #region Bằng tốt nghiệp

        [HttpGet]
        public ActionResult ThemBangtotnghiep()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemBangtotnghiep(BANGTOTNGHIEP bangTN)
        {
            if(ModelState.IsValid)
            {
                db.BANGTOTNGHIEPs.Add(bangTN);
                db.SaveChanges();
                //Tự động add thêm thông tin bangtotnghiep vào bảng HOCSINH
                int id_hs = (int)Session["id_hs"];
                HOCSINH hs = db.HOCSINHs.SingleOrDefault(n => n.id == id_hs);                
                //dua ra giay khai sinh vua them vào (nam ơ vi tri cuoi cung)
                BANGTOTNGHIEP newB = db.BANGTOTNGHIEPs.ToList().Last();
                hs.id_BTN = newB.id;
                //Lưu lại dữ liệu bảng Học Sinh
                db.Entry(hs).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bangTN);
        }

        #endregion end Bằng tốt nghiệp

        #region Học bạ, năm học, kì học
        [HttpGet]
        public ActionResult ThemHocba()
        {
            return View();

        }
        [HttpPost]
        public JsonResult XulyHocba(HOCBA hocba)
        {
            if(ModelState.IsValid)
            {
                 db.HOCBAs.Add(hocba);
                 db.SaveChanges();
                //Tự động add thêm thông tin hocba vào bảng HOCSINH
                int id_hs = (int)Session["id_hs"];
                HOCSINH hs = db.HOCSINHs.SingleOrDefault(n => n.id == id_hs);
                HOCBA NewH = db.HOCBAs.ToList().Last();
                hs.id_HB = NewH.id;
                //Lưu lại dữ liệu bảng Học Sinh
                db.Entry(hs).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return Json(hocba,JsonRequestBehavior.AllowGet);
            }
            return  Json(hocba,JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ThemNamhoc(NAMHOC namhoc)
        {
            if (ModelState.IsValid)
            {
                db.NAMHOCs.Add(namhoc);
               db.SaveChanges();
                return Json(namhoc, JsonRequestBehavior.AllowGet);
            }
            return Json(namhoc, JsonRequestBehavior.AllowGet);
        }
        //Thông tin kì học (Nhập điểm)
        [HttpGet]
        public JsonResult ViewNhapDiem(int id) //id: id_namhoc tuong ung
        {
            Session["id_namhoc"] = id;
            return Json(id,JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult NhapDiem(KIHOC kihoc)
        {
            if(ModelState.IsValid)
            {
                kihoc.id_NAMHOC =(int)Session["id_namhoc"];
                db.KIHOCs.Add(kihoc);
                db.SaveChanges();
                return Json(kihoc, JsonRequestBehavior.AllowGet);
            }
            return Json(kihoc, JsonRequestBehavior.AllowGet);
        }
        #endregion End Học bạ

        #region  Người giám hộ
        [HttpGet]
        public ActionResult ThemNguoigiamho()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemNguoigiamho(NGUOIGIAMHO ngh)
        {
            if(ModelState.IsValid)
            {
                ngh.id_HSinh = (int)Session["id_hs"];
                db.NGUOIGIAMHOes.Add(ngh);
                //Sau khi có thông tin học sinh và người giám hộ thì tự tạo hồ sơ HS
                HOSOH hosoHS = new HOSOH();
                hosoHS.id_HS = (int)Session["id_hs"];
                hosoHS.SoCMT_NGH = ngh.SoCMT;
                db.HOSOHS.Add(hosoHS);
                db.SaveChanges();

            }
            return View(ngh);
        }
         
        #endregion


        #region Uplooad_Image ... cần sửa lỗi
        [HttpPost]
        public JsonResult UploadImage()
        {
            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {             
                var fileImg = Request.Files["HelpSectionImages"];
            
                //lưu tên file
                var fileName = Path.GetFileName(fileImg.FileName);
                //lưu đường dẫn
                var path = Path.Combine(Server.MapPath("~/Content/img/profile"), fileName);
                // file is uploaded
                var type = fileImg.ContentType;
                if (System.IO.File.Exists(path))
                {
                    ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                }else{
                    if (type == "image/jpeg" || type == "image/jpg" || type == "image/png")
                        fileImg.SaveAs(path);                  
                }
                //dua ra hoc sinh can upload anh
                HOCSINH hs = db.HOCSINHs.ToList().Last();
                hs.anh = fileName;
                db.Entry(hs).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                //end
                return Json(fileName, JsonRequestBehavior.AllowGet);
           
            }
            return Json("Khong", JsonRequestBehavior.AllowGet);
        }
        #endregion


        #region Danh sách học sinh
        public ActionResult DanhsachHS()
        {           
            return View(db.HOCSINHs.ToList());
        }
        #endregion

        #region Search - học sinh
        [HttpPost]
        public ActionResult Search(string searchname)
        {
            List<HOCSINH> list_hs = new List<HOCSINH>();
            list_hs = db.HOCSINHs.Where(n => n.TenHS == searchname).ToList();
            return View(list_hs);
        }
        #endregion

      
    }
}

WebDoAnTN/Views/Quanlyhocsinh/CMT.cshtml
@{
    ViewBag.Title = "CMT";
    Layout = "~/Views/Shares/_Layout.cshtml";
}
<link href="~/Content/css/Cmt.css" rel="stylesheet" />
<h3>
    <a href="@Url.Action("Index","Quanlyhocsinh")"> Come back </a>
    <i class="fa fa-chevron-left"></i> Thông tin CMT
</h3>
<hr />

<div class="container cmt">
    <div class="row">
        <div class="col-sm-4 ">
            <img src="~/Content/img/CMT_1.jpg"/><br />
             
            <a href="#" id="1" onclick="LoaiCMT(1)">Loại 1</a>
        </div>
        <div class="col-sm-4">
            <img src="~/Content/img/CMT_2.jpg"/><br />
            <a href="#" id="2" onclick="LoaiCMT(2)">Loại 2</a>
        </div>
        <div class="col-sm-4">
            <img src="~/Content/img/CMT_3.jpg"/><br />
            <a href="#" id="3" onclick="LoaiCMT(3)">Loại 3</a>
        </div>

    </div>
</div>
<br />
<div class="loadCMT">
    
</div>
<script type="text/javascript">
    
    function LoaiCMT(type)
    {
        
        debugger;
        //alert(type);
        $.ajax({
            type: "GET",
            url: "/Quanlyhocsinh/LoadFormCMT",
            dataType: "json",
            data: "",
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                var row = '';
                row += '<form method="post" class="form-group" id="fm_cmt">';
                row += ' <div class="container formCmt">';
                row += '  <div class="row">';                                                  
                row += ' <div class="col-lg-5">';
                row += '<label for="SoCMT">Số CMT</label>';
                row += '<input type="text" name="SoCMT" id="SoCMT" class="form-control form-control-sm" />';

                row += '<label for="HoTen">Họ tên</label>';
                row += '<input type="text" name="HoTen" id="HoTen" class="form-control form-control-sm"/>';
                if (type == 2 || type == 3) {
                    row += '<label for="TenGoiKhac">Tên gọi khác</label>';
                    row += '<input type="text" name="TenGoiKhac" id="TenGoiKhac" class="form-control form-control-sm" />';
                }
                row += '<label for="NgaySinh">Ngày sinh</label>';
                row += '<input type="date" name="NgaySinh" id="NgaySinh" class="form-control form-control-sm" />';

                row += '<label for="QueQuan">Quê quán</label>';
                row += '<input type="text" name="QueQuan" id="QueQuan" class="form-control form-control-sm" />';
                row += '<label for="NoiThuongTru">Nơi thường trú</label>';
                row += '<input type="text" name="NoiThuongTru" id="NoiThuongTru" class="form-control form-control-sm" />';
                row += '</div>';

                row += ' <div class="col-lg-5">';
                if (type == 1) {
                    row += '<label  for="TonGiao">Tôn Giáo</label>'; row += '<label id="forDanToc"  for="DanToc">Dân tộc</label>';
                    row += '<input type="text" name="TonGiao" id="TonGiao" class="form-control form-control-sm"/>';
                    row += '<input type="text" name="DanToc" id="DanToc" class="form-control form-control-sm"/>';

                }
                if (type == 2) {
                    row += '<input checked="checked" id="Nam" name="GioiTinh" type="radio" value="Nam" /><span>Nam</span>';
                    row += '<input checked="checked" id="Nu" name="GioiTinh" type="radio" value="Nữ" /><span>Nam</span> <br/><br/><br/>';


                    row += '<label  for="GioiTinh">Giới tính</label>'; row += '<label id="forDanToc" for="DanToc">Dân tộc</label>';
                    row += '<input type="text" name="GioiTinh" id="GioiTinh" class="form-control form-control-sm" />';
                    row += '<input type="text" name="DanToc" id="DanToc" class="form-control form-control-sm" />';
                }
                if (type == 3) {
                    row += '<label for="GioiTinh">Giới tính</label>'; row += '<label id="forQuocTich" for="QuocTich">Quốc tịch</label>';
                    row += '<input type="text" name="GioiTinh" id="GioiTinh" class="form-control form-control-sm" />';                    
                    row += '<input type="text" name="QuocTich" id="QuocTich" class="form-control form-control-sm" />';
                }
                if (type == 2 || type == 3) {
                    row += '<label for="GiaTriDen">Giá trị đến</label>';
                    row += '<input type="date" name="GiaTriDen" id="GiaTriDen" class="form-control form-control-sm" />';
                }
                
                                               
                row += '<label for="DauVetRieng">Dấu vết riêng</label>';
                row += '<input type="text" name="DauVetRieng" id="DauVetRieng" class="form-control form-control-sm" />';
                row += '<label for="NgayCap">Ngày cấp</label>';
                row += '<input type="date" name="NgayCap" id="NgayCap" class="form-control form-control-sm" />';
                row += '<label for="NoiCap">Nơi cấp</label>';
                row += '<input type="text" name="NoiCap" id="NoiCap" class="form-control form-control-sm" />';                
                row += '</div>';
                row += '  </div>';
                row += '  </div>';
                row += '<input type="button" onclick="SaveCMT('+type+')" value="Lưu thông tin" class="btn btn-sm btn-primary" />';
                row += '</form>';
                $('.loadCMT').html(row);

            },
            error: function (err) {
            alert("Error: " + err.responseText);
        }
        });



    }

    function SaveCMT(type)
    {
        var cmt = {
            SoCMT: $('#SoCMT').val(),
            HoTen: $('#HoTen').val(),
            TenGoiKhac: $('#TenGoiKhac').val(),
            NgaySinh: $('#NgaySinh').val(),
            GioiTinh: $('#GioiTinh').val(),
            QuocTich: $('#QuocTich').val(),
            QueQuan: $('#QueQuan').val(),
            NoiThuongTru: $('#NoiThuongTru').val(),
            GiaTriDen: $('#GiaTriDen').val(),
            DanToc: $('#DanToc').val(),
            TonGiao: $('#TonGiao').val(),
            DauVetRieng: $('#DauVetRieng').val(),
            NgayCap: $('#NgayCap').val(),
            NoiCap: $('#NoiCap').val(),
            Type: type
        }
        debugger;
        $.ajax({
            type: "POST",
            url: "/Quanlyhocsinh/themCMT",
            dataType: "json",
            data: JSON.stringify(cmt),
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                console.log(data);
                $("#fm_cmt").css("display", "none");
            },
            error: function (err) {
                alert("Error: " + err.responseText);
            }
        });
    }

</script>

WebDoAnTN/Views/Quanlyhocsinh/DanhsachHS.cshtml
@model IEnumerable<WebDoAnTN.Models.HOCSINH>

@{
    ViewBag.Title = "DanhsachHS";
    Layout = "~/Views/Shares/_Layout.cshtml";
}

<h2>Danh sách học sinh</h2>
<hr />
<table class="table table-bordered" id="table_dshs" >
  <thead>
      <tr class="success">
          <th>Image</th>
          <th>Họ tên</th>
          <th>SĐT</th>
          <th>Email</th>
          <th>CMT</th>
          <th>Giấy khai sinh</th>
          <th>Bằng tốt nghiệp</th>
          <th>Thông tin khác</th>
      </tr>
  </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td><img class="img-circle" src="~/Content/img/profile/@item.anh" style="height:100px;width:150px;" /></td>
                <td><br /><br /><br /> @item.TenHS</td>
                <td><br /><br /><br /> @item.sdt</td>
                <td>
                    <br /><br /> @item.email <br />
                    <a href="#">Gửi mail</a>
                </td>
                <td><br /><br /><br /><a href="@Url.Action("ChitietCMT", "Xulyhocsinh", new {@id_hs =item.id })">CMT</a></td>
                <td><br /><br /><br /><a href="@Url.Action("ChitietGKS", "Xulyhocsinh", new { @id_hs = item.id })">GKS</a></td>
                <td><br /><br /><br /><a href="@Url.Action("ChitietBTN", "Xulyhocsinh", new { @id_hs = item.id })">BTN</a></td>
                <td><br /><br /><br /><a href="@Url.Action("Khac", "Xulyhocsinh", new { @id_hs = item.id })">Khác</a></td>
            </tr>
        }

    </tbody>
</table>

WebDoAnTN/Views/Quanlyhocsinh/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shares/_Layout.cshtml";
}

<h1>@Session["Loi"]</h1>

<h2>Nhập thêm thông tin học sinh </h2> <h4 style="color:#0094ff;">-----@Session["hocsinh"]------</h4>
<hr />
<a class="function" href="@Url.Action("CMT", "Quanlyhocsinh")">Chứng minh thư</a><br />
<a class="function" href="@Url.Action("ThemGiaykhaisinh", "Quanlyhocsinh")">Giấy khai sinh</a><br />
<a class="function" href="@Url.Action("ThemBangtotnghiep","Quanlyhocsinh")">Bằng tốt nghiệp</a><br />
<a class="function" href="@Url.Action("ThemHocba","Quanlyhocsinh")">Học bạ </a><br />
<a class="function" href="#">Người giám hộ</a><br />
<a class="function" href="#">Giấy chứng thực</a><br />

WebDoAnTN/Views/Quanlyhocsinh/ThemBangtotnghiep.cshtml
@{
    ViewBag.Title = "ThemBangtotnghiep";
    Layout = "~/Views/Shares/_Layout.cshtml";
}
<h3>
    <a href="@Url.Action("Index","Quanlyhocsinh")"> Come back </a>
    <i class="fa fa-chevron-left"></i> Thêm thông tin bằng tốt nghiệp
</h3>
<hr />
<form class="form-group" id="form_BTN" method="post">
    <label for="HoTen">Họ tên</label>
    <input type="text" name="HoTen" id="HoTen" value="@Session["hocsinh"]" class="form-control form-control-sm" />
    <label for="NgaySinh">Ngày sinh</label>
    <input type="date" name="NgaySinh" id="NgaySinh" class="form-control form-control-sm" />
    <label for="NoiSinh">Nơi sinh</label>
    <input type="text" name="NoiSinh" id="NoiSinh" class="form-control form-control-sm" />

    <label for="GioiTinh">Giới tính</label> <label id="forDanToc" for="DanToc">Dân tộc</label>

    <input type="text" name="GioiTinh" id="GioiTinh" class="form-control form-control-sm" />
    <input type="text" name="DanToc" id="DanToc" class="form-control form-control-sm" />


    <label for="KhoaThi">Khóa thi</label>
    <input type="date" name="KhoaThi" id="KhoaThi" class="form-control form-control-sm" />
    <label for="HoiDongThi">Hội đồng thi</label>
    <input type="text" name="HoiDongThi" id="HoiDongThi" class="form-control form-control-sm" />
     <label for="NgayLap">Ngày lập</label>
    <input type="text" name="NgayLap" id="NgayLap" class="form-control form-control-sm" />
    <label for="SoHieu">Số hiệu</label><label id="forSovaoSoCapBang" for="SovaoSoCapBang">Số vào số cấp Bằng</label>
    <input type="text" name="SoHieu" id="SoHieu" class="form-control form-control-sm" />
    
    <input type="text" name="SovaoSoCapBang" id="SovaoSoCapBang" class="form-control form-control-sm" /><br />

    <button type="submit" class="btn btn-sm btn-primary">Lưu thông tin</button>
</form>

WebDoAnTN/Views/Quanlyhocsinh/ThemGiaykhaisinh.cshtml
@{
    ViewBag.Title = "ThemGiaykhaisinh";
    Layout = "~/Views/Shares/_Layout.cshtml";
}
<h3>
    <a href="@Url.Action("Index","Quanlyhocsinh")"> Come back </a>
    <i class="fa fa-chevron-left"></i> Thêm thông tin giấy khai sinh
</h3>
<hr />
<form class="form-group" id="form_GKS" method="post">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <label for="HoTen">Họ tên</label>
                <input type="text" name="HoTen" id="HoTen" value="@Session["hocsinh"]" class="form-control form-control-sm" />
                <label for="NgaySinh">Ngày sinh</label>
                <input type="date" name="NgaySinh" id="NgaySinh" class="form-control form-control-sm" />
                <label for="NoiSinh">Nơi sinh</label>
                <input type="text" name="NoiSinh" id="NoiSinh"  class="form-control form-control-sm" />
                <label for="QueQuan">Quê quán</label>
                <input type="text" name="QueQuan" id="QueQuan"  class="form-control form-control-sm" />
                <label for="GioiTinh">Giới tính</label>
                <input type="text" name="GioiTinh" id="GioiTinh" class="form-control form-control-sm" />
                <label for="DanToc">Dân tộc</label> <label for="QuocTich" id="forQuocTich">Quốc tịch</label>
                <input type="text" name="DanToc" id="DanToc"  class="form-control form-control-sm" />               
                <input type="text" name="QuocTich" id="QuocTich"  class="form-control form-control-sm" />
                <label for="NoiDangKy">Nơi đăng ký</label>
                <input type="text" name="NoiDangKy" id="NoiDangKy" class="form-control form-control-sm" />
                <label for="NgapLap">Ngày lập</label>
                <input type="date" name="NgayLap" id="NgapLap" class="form-control form-control-sm" />

            </div>
            <div class="col-lg-6">
                <label for="HoTenMe">Họ tên mẹ</label>
                <input type="text" name="HoTenMe" id="HoTenMe" placeholder="Nhập tên mẹ " class="form-control form-control-sm" />
                <label for="NsMe">Năm sinh mẹ</label>
                <input type="text" name="NsMe" id="NsMe"class="form-control form-control-sm" />
                <label for="DanTocMe">Dân tộc mẹ</label><label id="forQuocTichMe" for="QuocTichMe">Quốc tịch mẹ</label>
                <input type="text" name="DanTocMe" id="DanTocMe" class="form-control form-control-sm" />              
                <input type="text" name="QuocTichMe" id="QuocTichMe" class="form-control form-control-sm" />
                <label for="NoiCuTruMe">Nơi cư trú mẹ</label>
                <input type="text" name="NoiCuTruMe" id="NoiCuTruMe" class="form-control form-control-sm" />
                <label for="HoTenBo">Họ tên bố</label>
                <input type="text" name="HoTenBo" id="HoTenBo" placeholder="Nhập tên bố " class="form-control form-control-sm" />
                <label for="NsBo">Năm sinh bố</label>
                <input type="text" name="NsBo" id="NsBo" class="form-control form-control-sm" />
                <label for="DanTocBo">Dân tộc bố</label><label id="forQuocTichBo" for="QuocTichBo">Quốc tịch bố</label>
                <input type="text" name="DanTocBo" id="DanTocBo" class="form-control form-control-sm" />
                
                <input type="text" name="QuocTichBo" id="QuocTichBo" class="form-control form-control-sm" />
                <label for="NoiCuTruBo">Nơi cư trú bố</label>
                <input type="text" name="NoiCuTruBo" id="NoiCuTruBo" class="form-control form-control-sm" />

            </div>
        </div>
    </div><br />
    <button type="submit" id="btn_gks" class="btn btn-sm btn-primary">Lưu thông tin</button>
</form>

WebDoAnTN/Views/Quanlyhocsinh/ThemNguoigiamho.cshtml
@{
    ViewBag.Title = "ThemNguoigiamho";
    Layout = "~/Views/Shares/_Layout.cshtml";
}

<h3>
    <a href="@Url.Action("Index","Quanlyhocsinh")"> Come back </a>
    <i class="fa fa-chevron-left"></i> Thêm thông tin người giám hộ
</h3><hr />
<div class="container">
    <form class="form-group" method="post" id="form_NGH">
        <div class="row">
            <div class="col-lg-5">
                <label for="SoCMT">Số CMT</label>
                <input type="text" name="SoCMT" id="SoCMT" class="form-control form-control-sm" />
                <label for="HoTen">Họ tên</label>
                <input type="text" name="HoTen" id="HoTen" class="form-control form-control-sm" /> 
                <div class="row">
                    <div class="col-lg-6">
                        <label for="NgaySinh">Ngày sinh</label>
                        <input type="date" name="NgaySinh" id="NgaySinh" class="form-control form-control-sm" />
                    </div>
                    <div class="col-lg-6">
                        <label for="GioiTinh" id="forGioiTinh" style="margin-left:32%;">Giới tính</label><br />
                        <div class="radio">
                            <label style="margin-left:10%;"><input type="radio" name="GioiTinh" value="Nam" id="GioiTinh" />Nam</label>
                            <label style="margin-left:25%;"><input type="radio" name="GioiTinh" value="Nữ" id="GioiTinh" />Nữ</label>
                        </div>                      
                    </div>
                </div>              
                
            </div>
            <div class="col-lg-1">
               </div>
            <div class="col-lg-5">
                <label for="QueQuan">Quê quán</label>
                <input type="text" name="QueQuan" id="QueQuan" class="form-control form-control-sm" />
                <label for="NoiThuongTru">Nơi thường trú</label>
                <input type="text" name="NoiThuongTru" id="NoiThuongTru" class="form-control form-control-sm" />
                <label for="NoiCap">Nơi cấp</label><label id="forNgayCap" for="NgayCap">Ngày cấp</label>
                <input type="text" name="NoiCap" id="NoiCap" class="form-control form-control-sm" />
                <input type="date" name="NgayCap" id="NgayCap" class="form-control form-control-sm" />

            </div>
        </div>
        <br />
        <button type="submit" class="btn btn-sm btn-primary" id="btn_NGH">Lưu thông tin</button>
    </form>
</div>